triton/chat: always add max_tokens
This seems to be required by Triton. Hardcode to 128k for now. This
value is rather high and most models won't be capable of handling it,
but it works around the following Triton error:

{"v":0,"name":"ai_router","msg":"[BACKEND::TRITON::CHAT::CHAT_COMPLETIONS - EVENT] ai_router::backend::triton::routes::chat","level":50,"hostname":"taz","pid":514911,"time":"2024-03-21T09:35:07.572241434Z","target":"ai_router::backend::triton::routes::chat","line":164,"file":"src/backend/triton/routes/chat.rs","error":"InternalServerError(\"error message received from triton: Traceback (most recent call last):\\n  File \\\"/shared/model_repo/Mistral-7B-Instruct-v0.2/1/model.py\\\", line 289, in execute\\n    raise pb_utils.TritonModelException(\\nc_python_backend_utils.TritonModelException: Failed to process the request(s) for model instance 'preprocessing_0_1', message: AttributeError: 'NoneType' object has no attribute 'as_numpy'\\n\\nAt:\\n  /shared/model_repo/preprocessing/1/model.py(149): execute\\n\\n\")"}