Cargo: bump openai_dive to 0.4.9
This seems to avoid the following panic:

thread 'tokio-runtime-worker' (1490979) panicked at /home/stijn/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/openai_dive-0.4.8/src/v1/helpers.rs:12:56:
called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)

This requires adding a new error type in transform_openai_dive_apierror.