errors: add InternalServerError variant to AiRouterError
And replace AppError with it.

With this, if Triton throws an error, we get the Triton error message in
an OpenAI compatible error format. E.g. when max_tokens is missing in
the request:

openai.InternalServerError: Error code: 500 - {'error': {'code': None, 'message': 'error message received from triton: Traceback (most recent call last):\n  File "/shared/model_repo/Mistral-7B-Instruct-v0.2/1/model.py", line 289, in execute\n    raise pb_utils.TritonModelException(\nc_python_backend_utils.TritonModelException: Failed to process the request(s) for model instance \'preprocessing_0_0\', message: AttributeError: \'NoneType\' object has no attribute \'as_numpy\'\n\nAt:\n  /shared/model_repo/preprocessing/1/model.py(149): execute\n\n', 'param': None, 'type': 'internal_server_error'}}

Previously this would also throw an internal server error, but without
useful info:

openai.InternalServerError: An error occurred while trying to fulfill your request.

Finally remove AppError as it has no more users.